name: flutter_youtube_player
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.8.0-dev <3.0.0"
  flutter: ">=1.14.6 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  intl:
  timeago:
  mono_kit: ^0.14.0-dev
  provider:
  google_fonts:
  vsync_provider:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
dependency_overrides:
  provider:
    git:
      url: https://github.com/rrousselGit/provider.git
      ref: extensions
flutter:
  uses-material-design: true
  assets:
    - assets/images/
